server:
  name: delivery-api

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: package org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl_auto: validate
  datasource:
    url: jdbc:mysql://localhost:33068/delivery?useSSL=false&useUnicode=true&PublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0805

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12